export const labels = {
  SelectAddressPlaceholder: "Selecione um endereço",
  PostalCodePlaceholder: "CEP",
  StreetPlaceholder: "Rua",
  StreetNumberPlaceholder: "Nº da Casa/Lote",
  SupplementPlaceholder: "Complemento",
  NeighborhoodPlaceholder: "Bairro",
  CityPlaceholder: "Cidade",
  StatePlaceholder: "Estado",
  CountryPlaceholder: "País",
  InvalidPostalCode: "CEP inválido.",
  BillingAddressLabel: "Endereço de faturamento",
  NewAddressLabel: "Cadastrar novo endereço",
  InvalidStreet: "Por favor, informe uma Rua válida.",
  InvalidStreetNumber: "Por favor, informe um Número válido.",
  InvalidNeighborhood: "Por favor, informe um Bairro válido.",
  InvalidCity: "Por favor, informe uma Cidade válida.",
  InvalidState: "Por favor, informe um Estado válido.",
  InvalidCountry: "Por favor, informe um País válido."
};